-- SELECT ID, IFNULL(CNT,0) AS CHILD_COUNT
-- FROM ECOLI_DATA AS E1
-- LEFT JOIN (SELECT PARENT_ID, COUNT(*) AS CNT
--       FROM ECOLI_DATA
--       GROUP BY PARENT_ID) AS E2
-- ON E1.ID = E2.PARENT_ID
-- ORDER BY ID


WITH CHILD_CNT AS (
    SELECT 
        PARENT_ID,
        COUNT(*) AS 'CHILD_CNT'
    FROM
        ECOLI_DATA 
    GROUP BY
        PARENT_ID)
    
SELECT
    ID,
    IFNULL(CHILD_CNT,0) AS 'CHILD_COUNT'
FROM
    ECOLI_DATA AS E
LEFT JOIN
    CHILD_CNT AS C
ON E.ID = C.PARENT_ID
ORDER BY
    ID
;