-- SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * M.T_AMOUNT AS TOTAL_SALES
-- FROM FOOD_PRODUCT AS P
-- JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS T_AMOUNT
--       FROM FOOD_ORDER 
--       WHERE PRODUCE_DATE LIKE '2022-05%'
--       GROUP BY PRODUCT_ID) AS M
-- ON P.PRODUCT_ID = M.PRODUCT_ID
-- ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID


WITH MAY_PRODUCE AS (
    SELECT
        PRODUCT_ID,
        SUM(AMOUNT) AS 'SUM_AMOUNT'
    FROM
        FOOD_ORDER
    WHERE
        PRODUCE_DATE LIKE '2022-05%'
    GROUP BY
        PRODUCT_ID)
        
SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.PRICE * M.SUM_AMOUNT AS 'TOTAL_SALES'
FROM
    FOOD_PRODUCT AS P
JOIN
    MAY_PRODUCE AS M USING(PRODUCT_ID)
ORDER BY
    TOTAL_SALES DESC, PRODUCT_ID ASC
;
