SELECT 
    YEAR(O.SALES_DATE) AS 'YEAR',
    MONTH(O.SALES_DATE) AS 'MONTH',
    I.GENDER,
    COUNT(DISTINCT I.USER_ID) AS 'USERS'
FROM
    USER_INFO AS I
JOIN
    ONLINE_SALE AS O
USING(USER_ID)
WHERE
    I.GENDER IS NOT NULL
GROUP BY
    YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), I.GENDER
ORDER BY
    YEAR, MONTH, I.GENDER
;