-- 1. 자동차 종류가 '트럭'인 경우에서, 렌트 기간 구하고, 기간마다 '7일 이상','30일 이상','90일 이상' 라벨링
-- 2. 할인율 테이블과 JOIN하여 각각에 해당하는 할인율 구하기
-- 3. 렌트 기간 * 일일 대여 요금 * 할인율 
    
WITH HISTORY_RENT_DAYS AS (
    SELECT 
        H.HISTORY_ID,
        H.CAR_ID,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS 'RENT_DAYS',
        CASE 
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
        END AS 'DURATION_TYPE'
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    JOIN CAR_RENTAL_COMPANY_CAR AS C
    ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT
    H.HISTORY_ID,
    ROUND(H.RENT_DAYS * R.DAILY_FEE * (1 - IFNULL(D.DISCOUNT_RATE,0)/100)) AS 'FEE'
FROM 
    HISTORY_RENT_DAYS AS H
JOIN 
    CAR_RENTAL_COMPANY_CAR AS R
ON H.CAR_ID = R.CAR_ID
LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
ON R.CAR_TYPE = D.CAR_TYPE
    AND H.DURATION_TYPE = D.DURATION_TYPE
ORDER BY 
    FEE DESC, HISTORY_ID DESC
;