SELECT 
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(S.SALES * B.PRICE) AS 'TOTAL_SALES'
FROM
    BOOK AS B
JOIN
    AUTHOR AS A
USING(AUTHOR_ID)
JOIN
    BOOK_SALES AS S
USING(BOOK_ID)
WHERE
    S.SALES_DATE LIKE '2022-01%'
GROUP BY
    A.AUTHOR_ID, B.CATEGORY
ORDER BY
    AUTHOR_ID ASC, CATEGORY DESC
;