-- 1. PARENT_ID가 NULL인 ID를 찾고 (ROOT)
-- 2. 1번에서 찾은 ID를 PARENT_ID로 가지는 ID를 찾고(2세대)
-- 3. 2번에서 찾은 ID를 PARENT_ID로 가지는 ID 찾기 = 3세대!

-- SELECT ID
-- FROM ECOLI_DATA
-- WHERE PARENT_ID IN (SELECT ID FROM ECOLI_DATA
--                     WHERE PARENT_ID IN (SELECT ID FROM ECOLI_DATA
--                                         WHERE PARENT_ID IS NULL))
-- ORDER BY ID ASC


SELECT
    THIRD_G.ID
FROM
    ECOLI_DATA AS FIRST_G
JOIN
    ECOLI_DATA AS SECOND_G
ON FIRST_G.ID = SECOND_G.PARENT_ID
JOIN
    ECOLI_DATA AS THIRD_G
ON SECOND_G.ID = THIRD_G.PARENT_ID
WHERE
    FIRST_G.PARENT_ID IS NULL
ORDER BY
    THIRD_G.ID
;