-- WITH ON_OFF_SALES AS 
-- (SELECT USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
-- FROM ONLINE_SALE
-- UNION ALL
-- SELECT NULL USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
-- FROM OFFLINE_SALE)

-- SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
-- FROM ON_OFF_SALES
-- WHERE SALES_DATE LIKE '2022-03%'
-- ORDER BY SALES_DATE, PRODUCT_ID, USER_ID


-- 1. 온라인에서 2022년 3월 판매데이터 구하기
-- 2. 오프라인에서 2022년 3월 판매데이터 구하기
-- 3. 둘 JOIN 

SELECT 
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS 'SALES_DATE',
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM
    ONLINE_SALE
WHERE
    SALES_DATE LIKE '2022-03%'
UNION ALL
SELECT
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS 'SALES_DATE',
    PRODUCT_ID,
    NULL AS USER_ID,
    SALES_AMOUNT
FROM
    OFFLINE_SALE
WHERE
    SALES_DATE LIKE '2022-03%'
ORDER BY
    SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC
;