-- SELECT CART_ID
-- FROM (SELECT CART_ID, NAME, COUNT(*) AS BUY_CNT
--       FROM CART_PRODUCTS
--       WHERE NAME IN ('Yogurt', 'Milk')
--       GROUP BY CART_ID, NAME) AS TARGET_ID
-- GROUP BY CART_ID
-- HAVING COUNT(*) >= 2
-- ORDER BY CART_ID

SELECT 
    CART_ID
FROM
    CART_PRODUCTS 
WHERE
    NAME IN ('Milk', 'Yogurt')
GROUP BY
    CART_ID
HAVING 
    COUNT(DISTINCT NAME) >= 2
ORDER BY
    CART_ID
;