-- SELECT ID, CASE 
--            WHEN R_SIZE <= 0.25 THEN 'CRITICAL'
--            WHEN R_SIZE <= 0.50 THEN 'HIGH'
--            WHEN R_SIZE <= 0.75 THEN 'MEDIUM'
--            ELSE 'LOW'
--        END AS COLONY_NAME 
-- FROM (SELECT ID, SIZE_OF_COLONY, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS R_SIZE
--       FROM ECOLI_DATA) AS PERCENT_RANK_SIZE
-- ORDER BY ID


SELECT 
    ID,
    CASE NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) -- NTILE(N) 사이즈를 N등분하는 함수
        WHEN 1 THEN 'CRITICAL' 
        WHEN 2 THEN 'HIGH'
        WHEN 3 THEN 'MEDIUM'
        WHEN 4 THEN 'LOW'
    END AS 'COLONY_NAME'
FROM
    ECOLI_DATA 
ORDER BY
    ID
;