SELECT 
    B.CATEGORY,
    SUM(S.SALES) AS TOTAL_SALES
FROM
    BOOK AS B
JOIN
    BOOK_SALES AS S ON B.BOOK_ID = S.BOOK_ID
WHERE 
    LEFT(S.SALES_DATE, 7) = '2022-01'
GROUP BY
    B.CATEGORY
ORDER BY
    B.CATEGORY
;