-- SELECT SUM(G.SCORE) AS SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
-- FROM HR_DEPARTMENT AS D
-- JOIN HR_EMPLOYEES AS E
-- ON D.DEPT_ID = E.DEPT_ID
-- JOIN HR_GRADE AS G
-- ON E.EMP_NO = G.EMP_NO
-- GROUP BY G.EMP_NO
-- ORDER BY SUM(G.SCORE) DESC
-- LIMIT 1
-- ;
-- 처음 풀 땐 왜 join 두번 했을까...?

SELECT 
    SUM(G.SCORE) AS SCORE,  -- 2022 상/하반기 점수 합하기
    EMP_NO,
    EMP_NAME,
    POSITION,
    EMAIL
FROM
    HR_EMPLOYEES AS E
JOIN 
    HR_GRADE AS G USING(EMP_NO)
WHERE 
    G.YEAR = '2022'
GROUP BY
    EMP_NO    
ORDER BY
    SCORE DESC
LIMIT 1
;