-- SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
-- FROM DEVELOPERS AS D
-- JOIN SKILLCODES AS S
-- ON S.NAME IN ('Python','C#')
-- WHERE D.SKILL_CODE & S.CODE > 0
-- ORDER BY D.ID ASC;


SELECT 
    ID,
    EMAIL,
    FIRST_NAME,
    LAST_NAME
FROM
    DEVELOPERS 
WHERE 
    SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME ='Python')
    OR 
    SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME ='C#')
ORDER BY
    ID
;